/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainForm.java
 *
 * Created on 28-nov-2009, 17.24.24
 */

package GUI;
import configurator.patchConfigurator.Configurator;
import db.mySQL.MySQLDataBase;
import log.fileLogger.FileLogger;
/**
 *
 * @author Luca
 * Main form di roboadmin
 */
public class MainForm extends javax.swing.JFrame {

    /** Creates new form MainForm */
    public MainForm() {
        initComponents();
        inizializza();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lowerPannel = new javax.swing.JPanel();
        AvvioRA = new javax.swing.JButton();
        jButtonStoppaRA = new javax.swing.JButton();
        mainTabPannel = new javax.swing.JTabbedPane();
        userPannel1 = new GUI.UserPannel();
        roboAdminPropertiesPannel1 = new GUI.RoboAdminPropertiesPannel();
        mySQLDBPropertiesPannel1 = new GUI.MySQLDBPropertiesPannel();
        mPPannel1 = new GUI.MPPannel();
        acceptPannel1 = new GUI.AcceptPannel();
        invalidStringPannel1 = new GUI.InvalidStringPannel();
        logPannel1 = new GUI.LogPannel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RoboAdmin");

        AvvioRA.setText("Avvio RA");
        AvvioRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvvioRAActionPerformed(evt);
            }
        });

        jButtonStoppaRA.setText("Stop RA");
        jButtonStoppaRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStoppaRAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lowerPannelLayout = new javax.swing.GroupLayout(lowerPannel);
        lowerPannel.setLayout(lowerPannelLayout);
        lowerPannelLayout.setHorizontalGroup(
            lowerPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lowerPannelLayout.createSequentialGroup()
                .addContainerGap(1039, Short.MAX_VALUE)
                .addComponent(jButtonStoppaRA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AvvioRA)
                .addContainerGap())
        );
        lowerPannelLayout.setVerticalGroup(
            lowerPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lowerPannelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lowerPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AvvioRA)
                    .addComponent(jButtonStoppaRA))
                .addContainerGap())
        );

        mainTabPannel.addTab("Users", userPannel1);
        mainTabPannel.addTab("RA Properties", roboAdminPropertiesPannel1);
        mainTabPannel.addTab("MySQLDB Properties", mySQLDBPropertiesPannel1);
        mainTabPannel.addTab("MP", mPPannel1);
        mainTabPannel.addTab("Accept", acceptPannel1);
        mainTabPannel.addTab("Invalid String", invalidStringPannel1);
        mainTabPannel.addTab("Log", logPannel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lowerPannel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainTabPannel, javax.swing.GroupLayout.DEFAULT_SIZE, 1203, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainTabPannel, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lowerPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AvvioRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvvioRAActionPerformed
        // TODO add your handling code here:
        try {
//            Viene avviato il thread che gestisce robo admin
            RoboThread=new RaThread("RoboAdmin",argo);
            RoboThread.start();
        }
        catch(Exception e){
            new ErrorForm("Problemi nell'avvio di RoboAdmin!\n"+e.toString()).setVisible(true);
        }

    }//GEN-LAST:event_AvvioRAActionPerformed

    private void jButtonStoppaRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStoppaRAActionPerformed
        // TODO add your handling code here:
        //stopa il thread di RoboThread va in eccezione ma per il momento è la scelta che è stata fatta inquanto resta comunque funzionante l'applicazione
        try{
            System.out.println("stato "+RoboThread.getState());
            //STOP è UN METODO DEPRECATO E NON FUNZIONA INQUANTO IL THREAD ROBOTHREAD RESTA NELLO STATO DI WAITING.
            RoboThread.getThreadGroup().stop();
        }
        catch(Exception e){
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_jButtonStoppaRAActionPerformed





    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) throws Exception {
        argo=args;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new MainForm().setVisible(true);
            }
        });
        
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AvvioRA;
    private GUI.AcceptPannel acceptPannel1;
    private GUI.InvalidStringPannel invalidStringPannel1;
    private javax.swing.JButton jButtonStoppaRA;
    private GUI.LogPannel logPannel1;
    private javax.swing.JPanel lowerPannel;
    private GUI.MPPannel mPPannel1;
    private javax.swing.JTabbedPane mainTabPannel;
    private GUI.MySQLDBPropertiesPannel mySQLDBPropertiesPannel1;
    private GUI.RoboAdminPropertiesPannel roboAdminPropertiesPannel1;
    private GUI.UserPannel userPannel1;
    // End of variables declaration//GEN-END:variables
    //Variabili di appoggio
    public static String argo[];
    RaThread RoboThread;
    //DB
    private Configurator conf=new Configurator();
    private MySQLDataBase db=null;
    private FileLogger log=new FileLogger();
//    private DBLogger logger=new DBLogger(db);

    //========================================================METODI PRIVATI DI INIZIALIZZAZIONE

    private void inizializza(){
       db= new MySQLDataBase(conf, log);
       userPannel1.inizializza(db);
       roboAdminPropertiesPannel1.inizializza(db);
       mySQLDBPropertiesPannel1.inizializza(db);
       mPPannel1.inizializza(db);
       acceptPannel1.inizializza(db);
       invalidStringPannel1.inizializza(db);
       logPannel1.inizializza(db);
    }


}
