/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MSNPProperty.java
 *
 * Created on 1-feb-2010, 13.23.42
 */

package GUI;


import configurator.patchConfigurator.Configurator;
import db.mySQL.MySQLDataBase;
import java.io.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.*;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import log.fileLogger.FileLogger;
/**
 *
 * @author Luca
 * Classe per la gestione di MSNProperty table
 */
public class MSNPProperty extends javax.swing.JFrame {

    /** Creates new form MSNPProperty */
    public MSNPProperty() {
        initComponents();
        inizializza();
        //IL BOTTONE DI AGGIUNTA DI UNA PROPRIETà è RESO INVISIBILE INQUANTO ANCHE SE SI PERMETTESSE L'AGGIUNTA DI UNA PROPERTY RA POI NON SAPREBBE
        //COME GESTIRLA PERTANTO è RESO INUSABILE
        jButtonNew.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        RoboAdminDBPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("RoboAdminDBPU").createEntityManager();
        msnppropertiesQuery = java.beans.Beans.isDesignTime() ? null : RoboAdminDBPUEntityManager.createQuery("SELECT m FROM Msnpproperties m");
        msnppropertiesList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(msnppropertiesQuery.getResultList());
        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanelsx = new javax.swing.JPanel();
        jLabelProperty = new javax.swing.JLabel();
        jLabelValue = new javax.swing.JLabel();
        jTextFieldProperty = new javax.swing.JTextField();
        jTextFieldValue = new javax.swing.JTextField();
        jButtonNew = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonSubmit = new javax.swing.JButton();
        jPaneldx = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMSNPProperties = new javax.swing.JTable();

        setTitle("MSNP Property");

        jPanel1.setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(250);

        jLabelProperty.setText("Property:");

        jLabelValue.setText("Value:");

        jButtonNew.setText("New");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelsxLayout = new javax.swing.GroupLayout(jPanelsx);
        jPanelsx.setLayout(jPanelsxLayout);
        jPanelsxLayout.setHorizontalGroup(
            jPanelsxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelsxLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jButtonSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonNew)
                .addContainerGap())
            .addGroup(jPanelsxLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelsxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelProperty)
                    .addComponent(jLabelValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelsxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldProperty)
                    .addComponent(jTextFieldValue, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanelsxLayout.setVerticalGroup(
            jPanelsxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelsxLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(jPanelsxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelProperty)
                    .addComponent(jTextFieldProperty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanelsxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValue)
                    .addComponent(jTextFieldValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(jPanelsxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNew)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonSubmit))
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanelsx);

        jPaneldx.setLayout(new java.awt.BorderLayout());

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, msnppropertiesList, jTableMSNPProperties);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${msnppropertiesPK.property}"));
        columnBinding.setColumnName("Property");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${msnppropertiesPK.value}"));
        columnBinding.setColumnName("Value");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTableMSNPProperties);
        jTableMSNPProperties.getModel().addTableModelListener(new TableModelListener() {
            public void tableChanged(TableModelEvent e) {
                int row = e.getFirstRow();
                int column=e.getColumn();
                ModificaDati(row,column);
            }
        });

        jPaneldx.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPaneldx);

        jPanel1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        // TODO add your handling code here:
        String NProperty=jTextFieldProperty.getText();
        String NValue=jTextFieldValue.getText();
        RendiPersistenteProprietà(NProperty,NValue);
        MSNPPropertiesListOld.add(new Msnpproperties(NProperty, NValue));
}//GEN-LAST:event_jButtonNewActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        String property=jTextFieldProperty.getText();
        String value=jTextFieldValue.getText();
        if (!(property.isEmpty() || value.isEmpty())){
            RimuoviRigaMSNPProperties(property,value);
        }
        int row=jTableMSNPProperties.getSelectedRow();
        if (row!=-1){
            RimuoviRigaMSNPProperties(row);
        } else{
            new ErrorForm("tupla non trovata");
        }
}//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        // TODO add your handling code here:
        Object [] dirtyRow=ModifiedRow.toArray();
        ModifiedRow.clear();
        for (int i=0; i<dirtyRow.length; i++){
            int row=Integer.parseInt(dirtyRow[i].toString());
            Object []Temp=new Object[jTableMSNPProperties.getColumnCount()];
            for (int j=0;j<jTableMSNPProperties.getColumnCount();j++){
                Temp[j]=jTableMSNPProperties.getValueAt(row, j);
            }
            String property=Temp[0].toString();
            String value=Temp[1].toString();
            try {
                Msnpproperties oldMSNPProperties=MSNPPropertiesListOld.get(row);
                String oldProperty=oldMSNPProperties.getMsnppropertiesPK().getProperty();
                String oldValue=oldMSNPProperties.getMsnppropertiesPK().getValue();
                RendiPersistenteModifica(oldProperty,oldValue,property,value);
            } catch(NumberFormatException e){
                new ErrorForm(e.toString());
            }
        }
        MSNPPropertiesListOld.clear();
        CopiaListaMSNPProperties(MSNPPropertiesListOld, msnppropertiesList);
}//GEN-LAST:event_jButtonSubmitActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MSNPProperty().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager RoboAdminDBPUEntityManager;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabelProperty;
    private javax.swing.JLabel jLabelValue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPaneldx;
    private javax.swing.JPanel jPanelsx;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTableMSNPProperties;
    private javax.swing.JTextField jTextFieldProperty;
    private javax.swing.JTextField jTextFieldValue;
    private java.util.List<GUI.Msnpproperties> msnppropertiesList;
    private javax.persistence.Query msnppropertiesQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    //Vartiabili di supporto per la gestione
    private Vector ModifiedRow=new Vector();
    private java.util.List<GUI.Msnpproperties> MSNPPropertiesListOld;
    private Configurator conf=new Configurator();
    private MySQLDataBase db=null;
    private FileLogger log=new FileLogger();

    //=========================================METODI PRIVATI DI INIZIALIZZAZIONE

    protected void inizializza(){
        MSNPPropertiesListOld=new ArrayList<Msnpproperties>();
        CopiaListaMSNPProperties(MSNPPropertiesListOld, msnppropertiesList);
        //prepara il db log sempre su file al momento
        db=new MySQLDataBase(conf, log);
    }

    //=========================================METODI PRIVATI PER LA GESTIONE DELLA TABELLA

    /**
    * Tiene traccia delle celle interesate da una modifica
    *
    * @param row riga
    * @param column colonna
    * @return void
    */
    private void ModificaDati(int row ,int column){
        //Invocato a ogni modifica della tabella
        //se la colonna modificata è -1 vuol dire che si sta aggiungendo togliendo una riga
        if (column!=-1){
            if (!ModifiedRow.contains(row))
            ModifiedRow.add(row);
        }
    }

       /**
    * Crea un lista con i dati della tabella di supporto al di andare a operare sulla giusta tubla anche se questa è stata modificata
    *
    * @param List<Accept> vecchi
    * @param List<Accept> nuovi
    * @return void
    */
    private void CopiaListaMSNPProperties(List<Msnpproperties> MSNPPropertiesOld,List<Msnpproperties> MSNPPropertiesNew){
         for (int i=0;i<MSNPPropertiesNew.size();i++){
            MSNPPropertiesOld.add(new Msnpproperties(MSNPPropertiesNew.get(i).getMsnppropertiesPK().getProperty(),MSNPPropertiesNew.get(i).getMsnppropertiesPK().getValue()));
        }
    }




   /**
    * Rende una nuova property persistente nel DB
    *
    * @param property la nuova propietà
    * @param value il valore della nuova proprietà
    * @return void
    */
    private void RendiPersistenteProprietà(String property, String value){
        //prepara la query da mandare al db
	String query ="INSERT INTO msnpproperties (Property, Value) VALUES ('" + property + "', '"+ value +"')";
        //esegue spedisce la query
        db.executeSqlUpdate(query);
        //AGGIUNGE LA RIGA DIRETTAMENTE ANCHE SULLA TABELLA
        Msnpproperties newMSNPProp = new Msnpproperties(property, value);
        msnppropertiesList.add(newMSNPProp);
        jTableMSNPProperties.repaint();
    }



     /**
    * Rimuove una tupla selezionata in base all'id inserito nel campo id dalla tabella e dal DB
    * @param property stringa contenente il nome della proprietà da rimuovere
    * @param value stringa contenente il valore associato alla proprietà da rimuovere
    * @return void
    */
    private void RimuoviRigaMSNPProperties(String property,String value) {
        //preparo la query di rimozione
	String query = "DELETE FROM msnpproperties WHERE Property= '" + property +"' AND Value= '" + value +"' ";
	//eseguo la query
        db.executeSqlUpdate(query);
        //RIMUOVE LA RIGA DALLA TABELLA
        Msnpproperties RProperty=new Msnpproperties(property,value);
        msnppropertiesList.remove(RProperty);
        jTableMSNPProperties.repaint();
    }
    /**
    * Rimuove una tupla selezionata nella tabella dal DB
    * @return void
    */
    private void RimuoviRigaMSNPProperties(int row){
        String property= (String) jTableMSNPProperties.getValueAt(row,0);
        String value=(String) jTableMSNPProperties.getValueAt(row, 1);
	//preparo la query
        String query = "DELETE FROM msnpproperties WHERE Property= '" + property +"' AND Value= '" + value +"' ";
	//eseguo la query
	db.executeSqlUpdate(query);
        //RIMUOVE LA RIGA DALLA TABELLA
        msnppropertiesList.remove(row);
        jTableMSNPProperties.repaint();
    }


     /**
    * Rende le modifiche apportate alle tuple sulla tabella persistenti sul DB, la ricerca della tupla da modificare è scolta in base a oldProperty e
    * oldValue
    * @param oldProperty stringa contenente il valore precedente alla modifica della propietà
    * @param oldValue stringa contenente il valore precedente alla modifica del value
    * @param property stringa contenente il valore aggiornato della propietà
    * @param value stringa contente il valore aggiornato del value
    * @return void
    */
    private void RendiPersistenteModifica(String oldProperty, String oldValue, String property, String value) {
        String query = "UPDATE msnpproperties SET Property= '" +property+"', Value= '"+ value +"' WHERE Property='"+ oldProperty +"' AND Value='"+ oldValue +"' ";
        //eseguo la query
        db.executeSqlUpdate(query);

    }

}
